(()=>{
  const VERSION='3.0.0-internal-state-sync31';
  const TEAM_ID='team::horn-capital-fc',BASELINE_LAST_DATE='2026-09-02';
  const norm=v=>String(v||'').toLocaleLowerCase('de-DE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const posCode=v=>{const p=String(v||'').toLowerCase();if(/^(tor|tw|goal)/.test(p))return'TW';if(/^(abwehr|abw|def)/.test(p))return'ABW';if(/^(mittelfeld|mf|mid)/.test(p))return'MF';if(/^(sturm|ang|attack|forward)/.test(p))return'ANG';return String(v||'')};
  const posLabel=v=>{const p=posCode(v);return p==='TW'?'Tor':p==='ABW'?'Abwehr':p==='MF'?'Mittelfeld':p==='ANG'?'Sturm':String(v||'')};
  const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
  function getData(){try{return data}catch{return null}}
  function active(){const d=getData();return (d?.players||[]).filter(p=>!p.soldDate)}
  function currentModel(){return window.H2H_CANONICAL_MODEL||null}
  function resolveMetadata(player){
    const m=currentModel(),key=norm(player.name);let local=null;try{if(typeof resolveShortNameAgainstLocalMasters==='function')local=resolveShortNameAgainstLocalMasters(player.name,{team:player.team||''})}catch{};try{if(!local&&typeof findSelectablePlayerByName==='function')local=findSelectablePlayerByName(player.name)}catch{}
    const ids=m?.indexes?.player_ids_by_normalized_name?.[key]||[];let entity=null,own=null;for(const pid of ids){const candidate=m?.entities?.players?.[pid];const ownership=m?.state?.current_ownership?.[pid];if(ownership?.team_id===TEAM_ID){entity=candidate;own=ownership;break}if(!entity)entity=candidate}
    const before=[player.name,player.team,player.position,player.marketValue].join('|');
    if(local?.name&&norm(player.name)===norm(local.name))player.name=local.name;
    if(!player.team&&local?.team)player.team=local.team;
    if(!player.position)player.position=posLabel(own?.position||entity?.positions_seen?.[0]||local?.position||'');
    if(!Number(player.marketValue)&&!player.soldDate)player.marketValue=Number(own?.market_value||local?.marketValue||0);
    return before!==[player.name,player.team,player.position,player.marketValue].join('|')
  }
  function enrichMetadata(){let changed=false;for(const p of getData()?.players||[])if(resolveMetadata(p))changed=true;return changed}
  function ensureCanonicalIdentity(player){
    const m=currentModel();if(!m)return null;m.entities=m.entities||{};m.entities.players=m.entities.players||{};m.indexes=m.indexes||{};m.indexes.player_ids_by_normalized_name=m.indexes.player_ids_by_normalized_name||{};const key=norm(player.name),known=m.indexes.player_ids_by_normalized_name[key]||[];let pid=known.length===1?known[0]:null;if(!pid){pid=`local::${hash(key||player.id)}`;m.entities.players[pid]=m.entities.players[pid]||{player_id:pid,display_name:player.name,normalized_name:key,positions_seen:[posCode(player.position)].filter(Boolean),identity_basis:'confirmed-local-transfer',identity_confidence:'high',notes:['Created after confirmed manager input.']};m.indexes.player_ids_by_normalized_name[key]=[...new Set([...(known||[]),pid])]}
    const e=m.entities.players[pid];e.display_name=player.name||e.display_name;e.normalized_name=key;if(player.position)e.positions_seen=[...new Set([...(e.positions_seen||[]),posCode(player.position)])].filter(Boolean);return pid
  }
  function dynamicEventExists(candidate){return (currentModel()?.events?.transfers||[]).some(e=>e?.manager_team_id===TEAM_ID&&e.direction===candidate.direction&&norm(e.player_name)===norm(candidate.player_name)&&Number(e.price||0)===Number(candidate.price||0)&&String(e.absolute_time||'').slice(0,10)===String(candidate.absolute_time||'').slice(0,10))}
  function makeEvent(player,direction,date,price,counterparty,eventSuffix){const pid=ensureCanonicalIdentity(player),cp=String(counterparty||'Kickbase'),time=`${date}T${direction==='BUY'?'12:00:00':'18:00:00'}+02:00`;return{event_id:`transfer::horn-local::${hash(`${player.id}|${direction}|${date}|${price}|${eventSuffix}`)}`,player_id:pid,player_name:player.name,manager_team_id:TEAM_ID,manager_team_name:'Horn Capital FC',direction,counterparty_type:/kickbase|transfermarkt/i.test(cp)?'kickbase':'manager',counterparty_team_id:null,counterparty_name:cp,price:Number(price)||0,absolute_time:time,relative_time:null,source_scope:'confirmed manager input / screenshot import',confidence:'high',h2hLocalDynamic:true}}
  function mirrorLocalEvents(){const d=getData(),m=currentModel();if(!d||!m)return false;m.events=m.events||{};m.events.transfers=Array.isArray(m.events.transfers)?m.events.transfers:[];let changed=false;for(const p of d.players||[]){if(p.h2hCanonicalHornVerified)continue;if(p.buyDate&&p.buyDate>BASELINE_LAST_DATE&&Number(p.buyPrice)){const e=makeEvent(p,'BUY',p.buyDate,p.buyPrice,p.buyCounterparty||p.buySource||'Kickbase','buy');if(!dynamicEventExists(e)){m.events.transfers.push(e);changed=true}}if(p.soldDate&&p.soldDate>BASELINE_LAST_DATE&&Number(p.salePrice)){const e=makeEvent(p,'SELL',p.soldDate,p.salePrice,p.saleCounterparty||p.saleSource||'Kickbase','sell');if(!dynamicEventExists(e)){m.events.transfers.push(e);changed=true}}}return changed}
  function syncCanonicalRoster(){const m=currentModel();if(!m)return false;m.state=m.state||{};m.state.current_squads=m.state.current_squads||{};m.state.current_ownership=m.state.current_ownership||{};m.indexes=m.indexes||{};m.indexes.players_by_current_team=m.indexes.players_by_current_team||{};const ids=[];for(const p of active()){const pid=ensureCanonicalIdentity(p);if(!pid)continue;ids.push(pid);m.state.current_ownership[pid]={player_id:pid,team_id:TEAM_ID,team_name:'Horn Capital FC',market_value:Number(p.marketValue)||0,position:posCode(p.position),snapshot_basis:'confirmed-local-state',confidence:'high'}}for(const[pid,own]of Object.entries(m.state.current_ownership))if(own?.team_id===TEAM_ID&&!ids.includes(pid))delete m.state.current_ownership[pid];const before=JSON.stringify(m.state.current_squads[TEAM_ID]||[]),next=[...new Set(ids)];m.state.current_squads[TEAM_ID]=next;m.indexes.players_by_current_team[TEAM_ID]=next;const team=m.entities?.teams?.[TEAM_ID];if(team){team.current_squad_size=next.length;team.current_squad_market_value=active().reduce((s,p)=>s+(Number(p.marketValue)||0),0)}return before!==JSON.stringify(next)}
  function syncLineupReferences(){const d=getData();if(!d)return false;const activeIds=new Set(active().map(p=>p.id));let changed=false;for(const r of d.matchdays||[]){const old=Array.isArray(r.lineup)?r.lineup:[],next=[...new Set(old.filter(id=>activeIds.has(id)))].slice(0,11);if(JSON.stringify(old)!==JSON.stringify(next)){r.lineup=next;changed=true}if(next.length<11&&r.formation){r.formation='';changed=true}}
    d.lineupIntel=d.lineupIntel||{};d.lineupIntel.pending=(d.lineupIntel.pending||[]).filter(x=>!x?.playerId||activeIds.has(x.playerId));d.ui=d.ui||{};d.ui.rosterSync={at:new Date().toISOString(),active:activeIds.size,currentMd:Number(d.settings?.currentMd)||1,lineup:(d.matchdays||[]).find(x=>Number(x.md)===Number(d.settings?.currentMd))?.lineup?.length||0};return changed
  }
  function audit(){const d=getData(),m=currentModel(),act=active(),missing=act.filter(p=>!p.team||!p.position).map(p=>p.name),current=(d?.matchdays||[]).find(x=>Number(x.md)===Number(d?.settings?.currentMd)),invalid=(current?.lineup||[]).filter(id=>!act.some(p=>p.id===id));const a={version:VERSION,checkedAt:new Date().toISOString(),transferRows:d?.players?.length||0,activePlayers:act.length,soldPlayers:(d?.players||[]).filter(p=>p.soldDate).length,currentLineupSize:(current?.lineup||[]).length,invalidLineupRefs:invalid,missingMetadata:missing,canonicalSquadSize:m?.state?.current_squads?.[TEAM_ID]?.length||0,ok:invalid.length===0&&missing.length===0};window.H2H_INTERNAL_SYNC_AUDIT=a;if(m){m.data_quality=m.data_quality||{};m.data_quality.internal_sync=a}return a}
  let running=false,lastRenderedActive='';
  function syncAll({reason='state-change',render:doRender=false}={}){if(running)return window.H2H_INTERNAL_SYNC_AUDIT||null;const d=getData();if(!d)return null;running=true;try{let changed=false;changed=enrichMetadata()||changed;changed=mirrorLocalEvents()||changed;changed=syncCanonicalRoster()||changed;changed=syncLineupReferences()||changed;const a=audit();d.ui=d.ui||{};d.ui.lastInternalSync={at:a.checkedAt,reason,ok:a.ok,active:a.activePlayers,lineup:a.currentLineupSize,missingMetadata:a.missingMetadata};if(changed){try{if(typeof save==='function')save()}catch(e){console.warn('[H2H] internal sync save failed',e)}}const activeSig=active().map(p=>`${p.id}:${p.soldDate||''}:${p.team}:${p.position}`).sort().join('|');const structural=activeSig!==lastRenderedActive;lastRenderedActive=activeSig;try{window.h2h300ReconcileOwnership?.()}catch(e){console.warn('[H2H] ownership after sync',e)}try{window.h2h300HornTransferCompleteness?.()}catch{}if((doRender||structural)&&typeof render==='function')setTimeout(()=>{try{render()}catch{}},30);window.dispatchEvent(new CustomEvent('h2h:state-synchronized',{detail:{reason,audit:a}}));return a}finally{running=false}}
  window.h2h300SyncAllDerivedState=syncAll;window.h2h300InternalSyncAudit=audit;
  let lastSig='';function watchSignature(){const d=getData();if(!d)return'';return JSON.stringify((d.players||[]).map(p=>[p.id,p.name,p.team,p.position,p.buyDate,p.buyPrice,p.soldDate,p.salePrice]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))))}
  setInterval(()=>{const sig=watchSignature();if(sig&&sig!==lastSig){lastSig=sig;syncAll({reason:'automatic-data-watch'})}},900);
  document.addEventListener('click',e=>{const text=String(e.target?.textContent||'');if(e.target?.id==='aiCommit'||/(speichern|übernehmen|verkauf|kauf)/i.test(text))setTimeout(()=>syncAll({reason:'confirmed-ui-change',render:true}),180)},true);
  setTimeout(()=>{try{window.h2h300SyncHornHistoryIntoTransfers?.({force:true})}catch{}syncAll({reason:'startup-reconcile',render:true});lastSig=watchSignature()},2200);
  console.info(`[H2H] ${VERSION} loaded`)
})();