(()=>{
  const VERSION='3.0.0-horn-transfer-history29';
  const TEAM_ID='team::horn-capital-fc';
  const EXPECTED_UNIQUE=72;
  const norm=v=>String(v||'').toLocaleLowerCase('de-DE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function eventKey(e){const d=e?.relative_time?.days_ago!=null?`d${e.relative_time.days_ago}`:e?.relative_time?.hours_ago!=null?`h${e.relative_time.hours_ago}`:String(e?.absolute_time||'');return [norm(e?.player_name),e?.direction,Number(e?.price)||0,d,norm(e?.counterparty_name)].join('|')}
  function rows(){const all=(window.H2H_CANONICAL_MODEL?.events?.transfers||[]).filter(e=>e?.manager_team_id===TEAM_ID);const seen=new Set(),out=[];for(const e of all){const k=eventKey(e);if(seen.has(k))continue;seen.add(k);out.push(e)}return out.sort((a,b)=>{const aa=Date.parse(a?.absolute_time||'')||0,bb=Date.parse(b?.absolute_time||'')||0;if(aa!==bb)return bb-aa;const ad=Number(a?.relative_time?.days_ago),bd=Number(b?.relative_time?.days_ago);if(Number.isFinite(ad)&&Number.isFinite(bd)&&ad!==bd)return ad-bd;const ah=Number(a?.relative_time?.hours_ago),bh=Number(b?.relative_time?.hours_ago);if(Number.isFinite(ah)&&Number.isFinite(bh)&&ah!==bh)return ah-bh;return String(b?.event_id||'').localeCompare(String(a?.event_id||''))})}
  function labelTime(e){if(e?.relative_time?.hours_ago!=null)return `vor ${e.relative_time.hours_ago} Std.`;if(e?.relative_time?.days_ago!=null)return `vor ${e.relative_time.days_ago} Tagen`;if(e?.absolute_time){const d=new Date(e.absolute_time);if(!Number.isNaN(d.getTime()))return d.toLocaleDateString('de-DE')}return 'Zeitpunkt unbekannt'}
  function report(){const list=rows(),complete=list.length===EXPECTED_UNIQUE;const r={version:VERSION,teamId:TEAM_ID,expectedUniqueEvents:EXPECTED_UNIQUE,canonicalUniqueEvents:list.length,complete,checkedAt:new Date().toISOString(),source:'Horn Capital FC.zip · 24 Screenshots · 72 eindeutige Transferereignisse'};window.H2H_HORN_TRANSFER_COMPLETENESS=r;const m=window.H2H_CANONICAL_MODEL;if(m){m.data_quality=m.data_quality||{};m.data_quality.horn_transfer_history=r}return r}
  function render(){let current;try{current=page}catch{current=null}if(current!=='transfers')return;const content=document.getElementById('content');if(!content)return;const list=rows(),r=report();let card=document.getElementById('h2hHornCanonicalTransfers300');if(!card){card=document.createElement('section');card.id='h2hHornCanonicalTransfers300';card.className='card';content.prepend(card)}
    const items=list.map(e=>`<div style="display:grid;grid-template-columns:minmax(130px,1fr) auto auto;gap:12px;align-items:center;padding:9px 0;border-top:1px solid rgba(127,127,127,.18)"><div><b>${esc(e.player_name||e.player_id||'Unbekannt')}</b><div class="muted">${esc(e.counterparty_name||'Kickbase')} · ${esc(labelTime(e))}</div></div><b style="white-space:nowrap">${e.direction==='SELL'?'Verkauf':'Kauf'}</b><b style="white-space:nowrap">${esc(euro(e.price))}</b></div>`).join('');
    card.innerHTML=`<div class="section-head"><div><h2>Verifizierte Horn-Transferhistorie</h2><p>Direkt aus den 24 Original-Screenshots · kanonische 3.0-Datenquelle</p></div><span class="badge ${r.complete?'good':'warn'}">${r.complete?'✓ Vollständig':'⚠ Unvollständig'}</span></div><div class="notice">Interne Prüfung: <b>${r.canonicalUniqueEvents}/${r.expectedUniqueEvents}</b> eindeutige Ereignisse vorhanden. ${r.complete?'Die ZIP und die kanonische Historie stimmen vollständig überein.':'Es fehlen Ereignisse oder es gibt zusätzliche, nicht belegte Einträge.'}</div>${items}`;
  }
  window.h2h300HornTransferCompleteness=report;window.h2h300RenderHornTransferHistory=render;
  const schedule=()=>setTimeout(render,50);document.addEventListener('click',schedule,true);window.addEventListener('hashchange',schedule);setInterval(render,1200);setTimeout(render,1500);console.info(`[H2H] ${VERSION} loaded`);
})();