(()=>{
  const VERSION='3.0.0-horn-history-adapter3',TEAM_ID='team::horn-capital-fc',BASELINE_LAST_DATE='2026-09-02';
  const EXPECTED_UNIQUE=72,EXPECTED_LIFECYCLES=43,EXPECTED_ACTIVE=14,EXPECTED_SOLD=29;
  const norm=v=>String(v||'').toLocaleLowerCase('de-DE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const seq=e=>{const m=String(e?.event_id||'').match(/(\d+)$/);return m?Number(m[1]):0};
  function eventKey(e){const d=e?.relative_time?.days_ago!=null?`d${e.relative_time.days_ago}`:e?.relative_time?.hours_ago!=null?`h${e.relative_time.hours_ago}`:String(e?.absolute_time||'');return[norm(e?.player_name),e?.direction,Number(e?.price)||0,d,norm(e?.counterparty_name)].join('|')}
  function events(){const all=(window.H2H_CANONICAL_MODEL?.events?.transfers||[]).filter(e=>e?.manager_team_id===TEAM_ID&&!e?.h2hLocalDynamic),seen=new Set(),out=[];for(const e of all){const k=eventKey(e);if(seen.has(k))continue;seen.add(k);out.push(e)}return out}
  function dateOf(e){const d=new Date(e?.absolute_time||'');return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
  function lifecycles(){const ordered=events().sort((a,b)=>{const ta=Date.parse(a?.absolute_time||'')||0,tb=Date.parse(b?.absolute_time||'')||0;if(ta!==tb)return ta-tb;return seq(b)-seq(a)}),open=new Map(),out=[];for(const e of ordered){const key=norm(e.player_name);if(e.direction==='BUY'){const row={id:`canonical-horn-${e.event_id}`,name:e.player_name,buyDate:dateOf(e),buyPrice:Number(e.price)||0,buyCounterparty:e.counterparty_name||'Kickbase',buyEventId:e.event_id,soldDate:'',salePrice:0,saleCounterparty:'',saleEventId:null};out.push(row);if(!open.has(key))open.set(key,[]);open.get(key).push(row)}else if(e.direction==='SELL'){const stack=open.get(key)||[],row=stack.length?stack.pop():null;if(row){row.soldDate=dateOf(e);row.salePrice=Number(e.price)||0;row.saleCounterparty=e.counterparty_name||'Kickbase';row.saleEventId=e.event_id}}}return out.sort((a,b)=>(b.buyDate||'').localeCompare(a.buyDate||'')||a.name.localeCompare(b.name,'de'))}
  function report(){const ev=events(),life=lifecycles(),active=life.filter(x=>!x.soldDate).length,sold=life.filter(x=>x.soldDate).length,r={version:VERSION,teamId:TEAM_ID,expectedUniqueEvents:EXPECTED_UNIQUE,canonicalUniqueEvents:ev.length,expectedLifecycles:EXPECTED_LIFECYCLES,canonicalLifecycles:life.length,expectedActive:EXPECTED_ACTIVE,active,expectedSold:EXPECTED_SOLD,sold,complete:ev.length===EXPECTED_UNIQUE&&life.length===EXPECTED_LIFECYCLES&&active===EXPECTED_ACTIVE&&sold===EXPECTED_SOLD,checkedAt:new Date().toISOString(),source:'Horn Capital FC.zip · 24 Screenshots'};window.H2H_HORN_TRANSFER_COMPLETENESS=r;const m=window.H2H_CANONICAL_MODEL;if(m){m.data_quality=m.data_quality||{};m.data_quality.horn_transfer_history=r}return r}
  function currentState(d){const rows=d?.players||[],baseline=rows.filter(p=>String(p?.buyDate||'')<=BASELINE_LAST_DATE),active=baseline.filter(p=>!p.soldDate).length,sold=baseline.filter(p=>p.soldDate).length;return{total:baseline.length,active,sold,allTotal:rows.length}}
  function removeLegacyBaselineDuplicates(d){const before=(d.players||[]).length;d.players=(d.players||[]).filter(p=>p?.h2hCanonicalHornVerified||String(p?.buyDate||'')>BASELINE_LAST_DATE);const removed=before-d.players.length;d.ui=d.ui||{};d.ui.hornLegacyBaselineCleanup={at:new Date().toISOString(),before,after:d.players.length,removed,rule:`canonical baseline through ${BASELINE_LAST_DATE}`};return removed}
  function needsRepair(d){const s=currentState(d);return s.total!==EXPECTED_LIFECYCLES||s.active!==EXPECTED_ACTIVE||s.sold!==EXPECTED_SOLD||(d.players||[]).some(p=>String(p?.buyDate||'')<=BASELINE_LAST_DATE&&!p?.h2hCanonicalHornVerified)}
  function sync({force=false}={}){const r=report(),core=window.H2H_STATE_CORE;if(!r.complete||!core?.mergeTransferLifecycles)return false;let d;try{d=data}catch{return false}const sig=`horn72-central:${r.canonicalUniqueEvents}:${r.canonicalLifecycles}:${r.active}:${r.sold}:v3`;if(!force&&!needsRepair(d)&&d?.ui?.hornCentralHistorySignature===sig)return true;core.mergeTransferLifecycles(lifecycles(),{expected:EXPECTED_LIFECYCLES});removeLegacyBaselineDuplicates(d);d.ui=d.ui||{};d.ui.hornCentralHistorySignature=sig;try{if(typeof save==='function')save()}catch{}core.syncAll({reason:'horn-history-adapter-v3',render:true});document.getElementById('h2hHornCanonicalTransfers300')?.remove();return !needsRepair(d)}
  window.h2h300HornTransferCompleteness=report;window.h2h300HornLifecycles=lifecycles;window.h2h300SyncHornHistoryIntoTransfers=sync;window.h2h300SyncHornHistoryToLegacyTable=sync;
  let tries=0,firstSuccessful=false,t=setInterval(()=>{tries++;if(window.H2H_STATE_CORE&&events().length>=EXPECTED_UNIQUE){const ok=sync({force:!firstSuccessful});firstSuccessful=true;if(ok)clearInterval(t)}if(tries>80)clearInterval(t)},250);
  document.addEventListener('click',()=>setTimeout(()=>{document.getElementById('h2hHornCanonicalTransfers300')?.remove();try{if(needsRepair(data))sync({force:true})}catch{}},60),true);
  console.info(`[H2H] ${VERSION} loaded`)
})();